### ISSUE TITLE
Crashing on 1.20.4

### ISSUE THREAD

**Issue by mindblaster0076** [Sindercube/Server-Unpacker#1]
Both of the releases are now crashing on 1.20.4, despite the description saying it works for 1.20.4.

**Comment by lumik0** [comment]
same

**Comment by czychuuu** [comment]
same

**Comment by PansanGG** [comment]
same

**Comment by Soumeh** [comment]
should be fixed with the latest release

**Comment by mindblaster0076** [comment]
I can confirm that this still does not work, and now the GUI does not either.
